name: Restore sanity backup

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo  "restore using this url ${{ github.event.inputs.url }}"
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          cd sanity
          yarn install
          yarn add @sanity/cli
      - name: test sanity command
        run:  npx -y sanity@latest sanity help
