name: Restore sanity backup

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'backup url'
        required: true
      targetDataset:
        description: 'target dataset'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          cd sanity
          yarn install
          npm install --global sanity@latest
      - name: run sanity import command
        run:  |
          set -e
          cd sanity
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_TOKEN }}" sanity dataset import ${{ github.event.inputs.url }} ${{ github.event.inputs.targetDataset }} --allow-assets-in-different-dataset
