name: Restore sanity backup

on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          cd sanity
          yarn install
          npm install --global sanity@latest
      - name: test sanity command
        run:  |
          set -e
          cd sanity
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_TOKEN }}" sanity dataset import https://sanitybackup1.s3.us-east-2.amazonaws.com/jmqfvlrp-production-2023-02-27.tar.gz test --allow-assets-in-different-dataset
